# Generated by Django 5.1.3 on 2024-11-07 12:14

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('star_actors', models.CharField(max_length=250)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('MOVIE', 'Movie'), ('TV SHOW', 'TV Show'), ('SERIES', 'series'), ('ANIMATION', 'animation'), ('CARTOON', 'cartoon'), ('ANIME', 'anime')], max_length=100)),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('ACTION', 'action'), ('COMEDEY', 'comedy'), ('THRILLER', 'thriller'), ('DRAMA', 'drama'), ('TRAGEDY', 'tragedy'), ('HORROR', 'horror'), ('SCI_FI', 'sci-fi'), ('FANTASY', 'fantasy'), ('ROMANCE', 'romance'), ('MUSICAL', 'musical')], max_length=100)),
                ('release_date', models.DateField()),
                ('parts', models.IntegerField(blank=True, default=1, null=True, verbose_name='parts/seasons')),
                ('episodes', models.IntegerField(blank=True, default=1, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
