# Generated by Django 5.1.3 on 2024-11-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='episodes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
