# Generated by Django 5.1.3 on 2024-11-07 14:11

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ACTION', 'action'), ('COMEDY', 'comedy'), ('THRILLER', 'thriller'), ('DRAMA', 'drama'), ('TRAGEDY', 'tragedy'), ('HORROR', 'horror'), ('SCI_FI', 'sci-fi'), ('FANTASY', 'fantasy'), ('ROMANCE', 'romance'), ('MUSICAL', 'musical')], max_length=100),
        ),
    ]
