# Generated by Django 5.1.3 on 2024-11-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_moviestar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='parts',
        ),
        migrations.AddField(
            model_name='movie',
            name='seasons',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
