# Generated by Django 5.1.3 on 2024-11-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_parts_movie_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='seasons',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
